version: "3"
services:
  nginx:
    image: nginx_image_lb
    container_name: nginx_container_lb
    build: ./nginx
    ports:
      - "8081:80" # HOST:CONTAINER
    expose:
      - 80
    links:
      - tomcat1:tomcat1 # SERVER_NAME:ANOTHER_NAME
      - tomcat2:tomcat2
      - tomcat3:tomcat3
    volumes:
      - ./webServer:/webserver
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - tomcat1 # first up tomcat1-3 -> nginx up
      - tomcat2
      - tomcat3

  tomcat1:
    build: ./tomcat
    ports:
      - "8001:8080"
    expose:
      - 8080
    volumes:
      - ./webServer/tomcat1:/usr/local/apache-tomcat-9.0.62/webapps/ROOT
  tomcat2:
    build: ./tomcat
    ports:
      - "8002:8080"
    expose:
      - 8080
    volumes:
      - ./webServer/tomcat2:/usr/local/apache-tomcat-9.0.62/webapps/ROOT
  tomcat3:
    build: ./tomcat
    ports:
      - "8003:8080"
    expose:
      - 8080
    volumes:
      - ./webServer/tomcat3:/usr/local/apache-tomcat-9.0.62/webapps/ROOT
